using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Abc.MvcWebUI.Entity
{
    public class DataInitializer : DropCreateDatabaseIfModelChanges<DataContext>
    {

        protected override void Seed(DataContext context)
        {

            var cinsiyetler = new List<Gender>()
            {
                new Gender(){ Name = "Woman"},
                new Gender(){ Name = "Man"},
                new Gender(){ Name = "Kids"},


            };

            foreach (var cinsiyet in cinsiyetler)
            {
                context.Genders.Add(cinsiyet);
            }
            context.SaveChanges();


            var markalar = new List<Brand>()
            {
                new Brand(){ Name = "Nike"},
                new Brand(){ Name = "Adidas"},


            };

            foreach (var marka in markalar)
            {
                context.Brands.Add(marka);
            }
            context.SaveChanges();


            var kategoriler = new List<Category>()
            {
                new Category(){ Name = "Casual", Description = "Casual Shoes"},
                new Category(){ Name = "Training", Description = "Training Shoes"},
                new Category(){ Name = "Running", Description = "Running Shoes"},

            };

            foreach (var kategori in kategoriler)
            {
                context.Categories.Add(kategori);
            }
            context.SaveChanges();

            var urunler = new List<Product>()
            {
              
                //kadn casual nike
                new Product(){ Name = "Nike V2K Run",Subtitle="woman shoes",Description ="Fast forward. Rewind. Doesn’t matter—this shoe takes retro into the future. The V2K remasters everything you love about the Vomero in a look pulled straight from an early aughts running catalog. Layer up in a mixture of flashy metallics, referential plastic details and a midsole with a perfectly vintage aesthetic. And the chunky heel makes sure wherever you go, it's in comfort.", Price = 110, Stock =100 , IsApproved =true , CategoryId = 1, IsHome= true , Image = "2fb6ff59-aca1-4f1f-a836-0888d4f119a6.jpg", Image2 = "03d951e6-cf6e-48e9-8404-2b342fc2825d.jpg" ,Image3 = "509edbec-df90-4229-9357-6dd5a5877975.jpg", genderId= 1, markaId=1},
                new Product(){ Name = "Nike Dunk Low LX NBHD", Subtitle="woman shoes",Description="The Dunk lineup welcomes yet another addition, enhancing your day with its harmonious and eye-catching style. This model seamlessly blends soft leather with denim fabric, creating a cohesive and attention-grabbing look.", Price = 110 , Stock =100 , IsApproved =true , CategoryId = 1, IsHome= true , Image = "d015d68b-1318-4c9d-bc79-9ac67c01cae4.jpg", Image2 = "5ca80c60-82c6-4c4e-bff5-052593ef7759.jpg" ,Image3 = "85655275-ae6a-43da-bb5c-877f1949f08e.jpg", genderId= 1, markaId=1},
                new Product(){ Name = "Nike Gamma Force",Subtitle="woman shoes", Description="Layers upon layers of dimensional style—that's a force to be reckoned with. Offering both comfort and versatility, these kicks are rooted in heritage basketball culture. The collar materials pay homage to vintage sport while the subtle platform elevates your look, literally. The Gamma Force is forging its own legacy: court style that can be worn all day, wherever you go.", Price = 90, Stock =100 , IsApproved =true , CategoryId = 1, IsHome= false , Image = "c82501e4-317d-4cc4-bd10-e7c947ce31a0.jpg", Image2 = "53692ee7-26db-4e4f-906f-45eeebc46ec4.jpg" ,Image3 = "43aec898-30ba-43c8-91dc-187a18117849.jpg", genderId= 1,markaId=1},
                new Product(){ Name = "Air Jordan 1 Low", Subtitle="woman shoes",Description="You tryna be comfortable all day, every day? We got you. The AJ1 Low has all the looks of the hoops original, with less weight and a sleek profile. Plus, they go with any 'fit—just lace up and go.", Price = 115, Stock =100 , IsApproved =true , CategoryId = 1, IsHome= false , Image = "air-jordan-1-low-ayakkabısı-1RBB3r.jpg", Image2 = "5671f9fd-8418-47b8-990b-14f5f8a920f4.jpg" ,Image3 = "air-jordan-1-low-ayakkabısı-1RBB3r (1).jpg", genderId= 1,markaId=1},
                new Product(){ Name = "Nike Tech Hera", Subtitle="woman shoes",Description="Inspired by early 2000s running, the Tech Hera is here to fulfill all of your chunky sneaker wishes. The wavy lifted midsole and suede accents level up your look while keeping you comfortable. Its durable design holds up beautifully to everyday wear—which is perfect, because you'll definitely want to wear these every day.", Price =110 , Stock =100 , IsApproved =true , CategoryId = 1, IsHome= true , Image = "6f796d34-61fc-453d-9715-1caa240b273f.jpg", Image2 = "3d6b13a2-4b2b-43c1-9de2-0d39331b5fd9.jpg" ,Image3 = "14f94151-edb8-41e1-a35e-9463069c1fed.jpg", genderId= 1,markaId=1},
                new Product(){ Name = "Nike Court Legacy Lift",Subtitle="woman shoes", Description="Elevate your style with the Nike Court Legacy Lift. Its platform midsole delivers a bold statement on top of a classic, easy-to-wear design. And don't worry, we've kept the fit you love.", Price = 90, Stock =100 , IsApproved =true , CategoryId = 1, IsHome= false , Image = "f5c33cc0-c240-4cd4-8437-1a58b2d3d6a1.jpg", Image2 = "eecaefa7-0d29-4efe-b671-3438dc6df887.jpg" ,Image3 = "900eb19c-2d7e-4657-9412-169b56ec9a37.jpg", genderId= 1,markaId=1},
                new Product(){ Name = "Nike TC 7900", Subtitle="woman shoes",Description="We've taken the look of early 2000s running and made it tough enough for everyday wear. By combining durable materials with soft cushioning, the TC 7900 is ready for your journey.", Price = 120, Stock =100 , IsApproved =true , CategoryId = 1, IsHome= true , Image = "9ecba19c-a2a3-4047-896e-46bbab267521.jpg", Image2 = "39029296-4157-4077-bb43-a56adb9c2239.jpg" ,Image3 = "b1161531-176e-44f3-9f6a-ceb07420ddf4.jpg", genderId= 1,markaId=1},
                new Product(){ Name = "Air Jordan 1 Elevate Low", Subtitle="woman shoes",Description="Rise to the occasion in style that soars. This shoe reworks an icon's original magic with a platform sole and low cut silhouette. Air cushioning keeps you lifted, and sleek leather in contrasting colors adds visual interest.", Price = 135, Stock =100 , IsApproved =true , CategoryId = 1, IsHome= true , Image = "5b5cd478-9beb-4754-8b5f-47b72055026b.jpg", Image2 = "7c7f9d71-4ddb-428f-937a-4f23dfd6091b.jpg" ,Image3 = "c67d98a4-c6f0-42a1-ab3e-764c1d0f341d.jpg", genderId= 1 ,markaId=1},
                new Product(){ Name = "Nike Zoom Air Fire",Subtitle="woman shoes", Description="With bold design lines and framed Zoom Air cushioning, the Nike Zoom Air Fire delivers a techy, unconventional look. Nodding to the history of performance running shoes, it defies classification with rich texturing, lots of layers and irreverent details that add to your defiant style.", Price = 125, Stock =100 , IsApproved =true , CategoryId = 1, IsHome= false , Image = "92b7be44-9043-43e5-a7f8-63cf1ce496be.jpg", Image2 = "1a766f6c-5ea7-4832-9632-5b24daa1d100.jpg" ,Image3 = "893d1d8d-d78f-497c-9c50-4b5147a6ad71.jpg", genderId= 1,markaId=1},
                new Product(){ Name = "Nike Waffle Debut", Subtitle="woman shoes",Description="Retro gets modernized with these sleek sneaks inspired by the Nike Daybreak. Era-echoing suede and nylon are paired in complementary colors, and the updated wedge midsole gives you an extra lift. Style, comfort, iconic Waffle outsole—this is a perfect new addition to your daily rotation.", Price = 75, Stock =100 , IsApproved =true , CategoryId = 1, IsHome= false , Image = "e43bc784-567b-4ed3-9c22-498bf7ca7f0f.jpg", Image2 = "fef3a7d5-f71e-470c-b9eb-dc707ab9a645.jpg" ,Image3 = "22e935a8-5fd6-4de2-89dc-f292a0054d6d.jpg", genderId= 1,markaId=1},
                new Product(){ Name = "Nike Court Vision Alta", Subtitle="woman shoes",Description="Nike Court Vision Alta", Price = 90, Stock =100 , IsApproved =true , CategoryId = 1, IsHome= false , Image = "df2b8e99-04ef-4fc0-9829-ede777268337.jpg", Image2 = "08df9eba-6e98-4919-8ef1-caca5a7d6b18.jpg" ,Image3 = "4ce5a724-2754-4790-b847-4ddf4ef448f0.jpg", genderId= 1,markaId=1},

                //kadın training nike
                new Product(){ Name = "Nike Metcon 9 AMP", Subtitle="woman shoes",Description="Whatever your \"why\" is for working out, the Metcon 9 makes it all worth it. We improved on the 8 with a larger Hyperlift plate and added rubber rope wrap. Sworn by some of the greatest athletes in the world, intended for lifters, trainers, go-getters, it’s still the gold standard that delivers day after day. This balanced, vitamin-inspired design radiates with the vibrant energy you bring to your workout and those around you.", Price = 160, Stock =100 , IsApproved =true , CategoryId = 2, IsHome= false , Image = "8d3ec4e3-a62a-46ba-a8cd-dc34f3270101.jpg", Image2 = "91e1ca3d-de38-4e13-be1b-3926df9f1a16.jpg" ,Image3 = "35f86528-53b4-4d4b-b7e0-a5525d2b75f9.jpg", genderId= 1,markaId=1},
                new Product(){ Name = "Nike In-Season TR 13",Subtitle="woman shoes", Description="When time is of the essence, but your workout can’t wait any longer, ride with the Nike In-Season TR 13. It offers versatility, the kind that can carry you from a hard-hitting HIIT class to the treadmill and turn a squeezed-in gym session into sweat-soaked satisfaction. Whether you’re moving laterally or deepening your cardio base by reeling in a few miles in front of you, the energy return will help you reap what you sow.", Price = 85, Stock =100 , IsApproved =true , CategoryId = 2, IsHome= false , Image = "f2d8e116-6108-437d-b135-9b6cdcd463bb.jpg", Image2 = "in-season-tr-13-antrenman-ayakkabısı-qkQTD2.jpg" ,Image3 = "e56667e1-2e5a-4ef2-ae8c-7c5d568a5902.jpg", genderId= 1,markaId=1},
                new Product(){ Name = "Nike Zoom Bella 6", Subtitle="woman shoes",Description="Unleash your power and spirit with the Nike Zoom Bella 6. This design supports your post-workout cool-down, showcasing the successes you've earned through weightlifting exercises, explosive movements, and pushing your limits in the gym. The newly implemented Zoom Air cushioning provides support, while the revamped arch accommodates any foot shape, allowing you to train without compromising on style.", Price = 90, Stock =100 , IsApproved =true , CategoryId = 2, IsHome= false , Image = "f1419e6a-8410-42e5-a1af-e6c4410aa190.jpg", Image2 = "7523b1be-8a68-485a-933e-36303d3422c0.jpg" ,Image3 = "ed1a6946-d71f-4b32-b4f0-1af7b5a18b4b.jpg", genderId= 1,markaId=1},
                new Product(){ Name = "Nike Free Metcon 5",Subtitle="woman shoes", Description="When your workouts wade into the nitty gritty, the Nike Free Metcon 5 can meet you in the depths, help you dig deep to find that final ounce of force and come out of the other side on a high. It matches style with substance, forefoot flexibility with backend stability, perfect for flying through a cardio day or enhancing your agility. A revamped upper offers easier entry with a collar made just for your ankle.", Price =120 , Stock =100 , IsApproved =true , CategoryId = 2, IsHome= false , Image = "3b1c0c7f-a895-49e2-bbaa-7ded55eaa2ee.jpg", Image2 = "1044f0a8-8d88-4f8e-93db-9ff0da404e85.jpg" ,Image3 = "7393db27-38ca-4387-a863-3fccfee68ecd.jpg", genderId= 1,markaId=1},
                new Product(){ Name = "Nike Metcon 8",Subtitle="woman shoes", Description="You chase the clock, challenging and encouraging each other all in the name of achieving goals and making gains. Our go-to model for training relies on a lighter, more breathable upper than our previous edition to complement our standards of durability and comfort, so that you can float through your cardio, power through your lifts and dominate your workouts.", Price = 130, Stock =100 , IsApproved =true , CategoryId = 2, IsHome= false , Image = "f3408887-7dce-4d3a-a895-6b6e9a2c1132.jpg", Image2 = "metcon-8-antrenman-ayakkabısı-H47LFH.jpg" ,Image3 = "fe343b90-8bb4-4511-9d04-8a782f1b0fac.jpg", genderId= 1,markaId=1},
                new Product(){ Name = "Nike Legend Essential 3 Next Nature", Subtitle="woman shoes",Description="Meet the trainer versatile enough to withstand the rigors of a fast-paced group class or a heavy day in the weight room. Equipped with a flat heel, high-abrasion materials and a flexible sole, it provides comfort and support that's ready to hit the gym. See the specks on the outsole? That means it's constructed with at least 8% Nike Grind material, made from scraps from the footwear manufacturing process.﻿", Price = 65, Stock =100 , IsApproved =true , CategoryId = 2, IsHome= true , Image = "legend-essential-3-next-nature-antrenman-ayakkabısı-fZj9ZC.jpg", Image2 = "legend-essential-3-next-nature-antrenman-ayakkabısı-fZj9ZC (1).jpg" ,Image3 = "edcbbe7d-f37c-40cb-b06d-5130d22e171f.jpg", genderId= 1,markaId=1},
                new Product(){ Name = "Nike Free RN NN",Subtitle="woman shoes", Description="If it’s freedom you crave, this road runner can help turn you loose. Feathery and flexible, its barefoot feel and Flyknit upper will have you freewheeling with joy, ready to go a few more strides.", Price = 100, Stock =100 , IsApproved =true , CategoryId = 2, IsHome= false , Image = "9a127777-bee7-4176-a5f3-7d1c91934135.jpg", Image2 = "935c0a70-433f-4473-ba56-ab52ea1a73e8.jpg" ,Image3 = "f111a89f-6abd-46fc-ba1b-25139f7d7f14.jpg", genderId= 1,markaId=1},
                new Product(){ Name = "Nike Zoom SuperRep 4 Next Nature", Subtitle="woman shoes",Description="The quad-burning box jumps that bring your “why” into focus. The sweat-soaked super-sets that leave you grabbing your tights. This is what you live for: the struggle, the moment of truth, the breakthrough, the transformation. Designed for quick bursts of force, heart-thumping tempo changes and fast-paced workouts, this trainer helps push you to fresh HIIT heights.", Price = 130, Stock =100 , IsApproved =true , CategoryId = 2, IsHome= false , Image = "e4a9be08-d8ab-472e-b5c4-42dccc7adb05.jpg", Image2 = "23f3e113-22b4-469e-90cb-c368bca39e77.jpg" ,Image3 = "d8326a3d-b58f-4514-8d84-8da446e5c646.jpg", genderId= 1,markaId=1},
                new Product(){ Name = "Nike SuperRep Go 3 Flyknit Next Nature", Subtitle="woman shoes",Description="The new Nike SuperRep Go 3 Flyknit is a radical design story rooted in innovation. Made with at least 20% recycled content by weight, the zoned Flyknit construction wraps your foot in 360 degrees of comfort and support. A finely ground, reclaimed foam midsole gives you responsive cushioning for high-impact training. The lightweight, packable design lets you keep them close, no matter where your next workout takes you.", Price =100 , Stock =100 , IsApproved =true , CategoryId = 2, IsHome= false , Image = "cba4153d-f758-47a5-810f-4bd1269121fa.jpg", Image2 = "superrep-go-3-flyknit-next-nature-womens-workout-shoes-hSZBdX.jpg" ,Image3 = "6eb1cd60-0572-4ff2-b561-7bf20e1d80c6.jpg", genderId= 1,markaId=1},
                new Product(){ Name = "Nike Air Max Bella TR 5", Subtitle="woman shoes",Description="The Nike Air Max Bella TR 5 Premium combines the bounce and beauty of Max Air cushioning with a flat sole that lends a stabilizing advantage while you tone and sculpt with weight. This updated design increases the containment and support around the sides and top of your foot to help keep you steady on your feet and secure during demanding strength workouts.", Price = 90, Stock =100 , IsApproved =true , CategoryId = 2, IsHome= false , Image = "90cfd816-0084-440b-a16e-1fe1b053169e.jpg", Image2 = "air-max-bella-tr-5-womens-workout-shoes-tLCg4B.jpg" ,Image3 = "8833144f-823c-40a1-90e2-f893d9bdd901.jpg", genderId= 1,markaId=1},

                //kadın running nike
                new Product(){ Name = "Nike Pegasus Shield", Subtitle="woman shoes",Description="Your workhorse with wings returns to help you push through the rain. A water-repellent finish helps keep you dry while a cozy fleece-like feel on the inside helps keep your feet warm for nasty-weather runs. Rugged traction and 2 Zoom Air units provide grip and soft cushioning, so you can power through the elements.", Price =145 , Stock =100 , IsApproved =true , CategoryId = 3, IsHome= false , Image = "6a480dac-3678-4417-b877-8fdcd3216865.jpg", Image2 = "pegasus-shield-hava-şartlarına-dayanıklı-yol-koşu-ayakkabısı-Npkkgv.jpg" ,Image3 = "b56dcc9e-4128-4941-9f1a-8cce6f731a39.jpg", genderId= 1,markaId=1},
                new Product(){ Name = "Nike InfinityRN 4 GORE-TEX",Subtitle="woman shoes", Description="With supportive cushioning built for a smooth run, the Nike InfinityRN 4 is a brand-new take on a familiar favorite. It's made from our all-new Nike ReactX foam, which gives you 13% more energy return compared with Nike React foam, to help you stay fresh and bouncy. (What's more? Nike ReactX reduces its carbon footprint in a pair of midsoles by at least 43% compared to Nike React foam.*) This version has GORE-TEX fabric to help you stay dry for your miles. It’s the kind of shoe that supports every step in style. *The carbon footprint of ReactX is based on cradle-to-gate assessment reviewed by PRé Sustainability B.V and Intertek China. Other midsole components such as airbags, plates or other foam formulations were not considered.", Price = 180, Stock =100 , IsApproved =true , CategoryId = 3, IsHome= true , Image = "e4170bf1-6073-416a-bcda-6015bf0e4626.jpg", Image2 = "5269f39f-3b24-4e28-bf1e-a4c8f03886b4.jpg" ,Image3 = "d3d9a013-77b5-4fa8-9105-ae2109753d29.jpg", genderId= 1,markaId=1},
                new Product(){ Name = "Nike Juniper Trail 2 GORE-TEX", Subtitle="woman shoes",Description="The Juniper Trail 2 has waterproof GORE-TEX on the upper, grippy traction and a soft, cushiony midsole. It helps keep your toes dry when the trail conditions are splashy and sleety.", Price =130 , Stock =100 , IsApproved =true , CategoryId = 1, IsHome= false , Image = "juniper-trail-2-gore-tex-su-geçirmez-arazi-tipi-koşu-ayakkabısı-2rnGqT.jpg", Image2 = "juniper-trail-2-gore-tex-su-geçirmez-arazi-tipi-koşu-ayakkabısı-2rnGqT (1).jpg" ,Image3 = "85066b73-904b-46a2-958d-475dee2a7fbf.jpg", genderId= 1,markaId=1},
                new Product(){ Name = "Nike Pegasus Trail 4 GORE-TEX", Subtitle = "woman shoes", Description="The Nike Pegasus Trail 4 GORE-TEX is made for those moments when you don't want to turn back, no matter what. Feel confident even in the most unforeseen weather conditions with waterproof GORE-TEX keeping you dry, so you can run harder for longer and take your wet run from the road to the trail without breaking stride. A waterproof layer paired with a higher ankle gaiter gives you extra coverage so you stay dry.", Price = 160, Stock =100 , IsApproved =true , CategoryId = 3, IsHome= false , Image = "pegasus-trail-4-gore-tex-su-geçirmez-arazi-tipi-koşu-ayakkabısı-T6hRF0.jpg", Image2 = "75129e44-3229-45b1-84a3-d9331b9049b9.jpg" ,Image3 = "fb7757bf-a7d5-4cc5-b02d-e4e2fa5f566a.jpg", genderId= 1,markaId=1},
                new Product(){ Name = "Nike Air Winflo 9 Shield", Subtitle = "woman shoes", Description="Nasty weather doesn’t need to put an end to your run. Revel in the elements with these shoes designed to help you push through every puddle, pit stop, pothole and personal record. A water-repellent finish helps keep you dry while tire-like traction and a full-length Air unit provide grip and soft cushioning to help keep you running when conditions get slick.", Price = 115, Stock =100 , IsApproved =true , CategoryId = 3, IsHome= false , Image = "8abf1372-0b4a-4c28-aa80-1e06175e68da.jpg", Image2 = "b5c12cb2-11a9-4d8e-94d5-01872c75b564.jpg" ,Image3 = "4a29c65e-93ce-46d6-9f25-9c24630c54d2.jpg", genderId= 1,markaId=1},
                new Product(){ Name = "Nike Pegasus 40", Subtitle="woman shoes",Description="A springy ride for any run, the Peg’s familiar, just-for-you feel returns to help you accomplish your goals. This version has the same responsiveness and neutral support you love, but with improved comfort in those sensitive areas of your foot, like the arch and toes. Whether you’re logging long marathon miles, squeezing in a speed session before the sun goes down or hopping into a spontaneous group jaunt, it’s still the established road runner you can put your faith in, day after day, run after run.", Price = 130, Stock =100 , IsApproved =true , CategoryId = 3, IsHome= true , Image = "e462698f-a806-4b9f-980b-cdd06c4c43b8.jpg", Image2 = "b855ac19-a8ce-4253-a799-896415124895.jpg" ,Image3 = "47250c04-a48c-4423-ae73-8bf0a50392db.jpg", genderId= 1,markaId=1},
                new Product(){ Name = "Nike Juniper Trail 2 Next Nature", Subtitle = "woman shoes", Description="\r\nThe Nike Juniper Trail 2 breaks molds and invites you to explore captivating terrains. With its durable upper and robust traction on the lower part, it provides a consistent and confident user experience for trail runs in the terrains you want to conquer. Developed for off-road landscapes and undiscovered paths, this style ensures a reliable grip to help you finish your run with confidence.", Price =100 , Stock =100 , IsApproved =true , CategoryId = 3, IsHome= true , Image = "2bc84f5a-6be7-442c-943e-abc0226a3af2.jpg", Image2 = "b1aa239e-6f24-4d50-bcc8-d02f0e8acb41.jpg" ,Image3 = "f100d382-7d3d-4849-8fd7-53310a44d08b.jpg", genderId= 1,markaId=1},
                new Product(){ Name = "Nike Revolution 7", Subtitle = "woman shoes", Description="We loaded the Revolution 7 with the sort of soft cushioning and support that might change your running world. Stylish as ever, comfortable when the rubber meets the road, and performative for your desired pace, it’s an evolution of a fan favorite that offers a soft, smooth ride.", Price =70 , Stock =100 , IsApproved =true , CategoryId = 1, IsHome= false , Image = "d76b79fd-e11d-458d-8177-fa1746921e21.jpg", Image2 = "53674c8e-c952-4d5b-8e4c-bf1868e90173.jpg" ,Image3 = "f3b57dd1-23a3-45c6-9fc2-9e0a2657fe05.jpg", genderId= 1,markaId=1},
                new Product(){ Name = "Nike Downshifter 12", Subtitle = "woman shoes", Description="Take those first steps on you running journey in the Nike Downshifter 12. It's got a supportive fit and a stable ride, with a lightweight feel that easily transitions from your workout to hanging out. This one continues our sustainability journey with a design made from at least 20% recycled content by weight. Your trek begins. Lace up and hit the road.", Price = 70, Stock =100 , IsApproved =true , CategoryId = 3, IsHome= false , Image = "downshifter-12-yol-koşu-ayakkabısı-L3TXTF.jpg", Image2 = "downshifter-12-yol-koşu-ayakkabısı-L3TXTF (1).jpg" ,Image3 = "d890de82-95ba-457d-90da-c10c6b833254.jpg", genderId= 1,markaId=1},
                new Product(){ Name = "Nike InfinityRN 4", Subtitle = "woman shoes", Description="With supportive cushioning built for a smooth run, the Nike InfinityRN 4 is a brand-new take on a familiar favorite. It's made from our all-new Nike ReactX foam, which gives you 13% more energy return compared with Nike React foam, to help you stay fresh and bouncy. (What's more? Nike ReactX reduces its carbon footprint in a pair of midsoles by at least 43% compared to Nike React foam.*) We coupled the ReactX foam with Nike Running's best-fitting Flyknit yet, so you can feel confident in every stride with soft upper support and breathability. It’s the kind of shoe that supports every step in style. *The carbon footprint of ReactX is based on cradle-to-gate assessment reviewed by PRé Sustainability B.V and Intertek China. Other midsole components such as airbags, plates or other foam formulations were not considered.", Price = 160, Stock =100 , IsApproved =true , CategoryId = 3, IsHome= false , Image = "14cbeb44-6889-4e22-9f3c-a7dd46e7a639.jpg", Image2 = "30821d14-ee66-4027-8ae0-96dce3b1c09f.jpg" ,Image3 = "d3bd8eb7-0630-4181-8a34-b9aad4f1b846.jpg", genderId= 1,markaId=1},
                //woman running adidas
                new Product() { Name = "Adidas CLOUDFOAM", Subtitle = "Woman shoes", Description = "Adidas CLOUDFOAM Lifestyle Running Gray", Price = 160, Stock = 100, IsApproved = true, CategoryId = 2, IsHome = false, Image = "Ozelle_Cloudfoam_Lifestyle_Running_Ayakkabi_Gri_IG9797_06_standard.jpg", Image2 = "Ozelle_Cloudfoam_Lifestyle_Running_Ayakkabi_Gri_IG9797_02_standard.jpg", Image3 = "Ozelle_Cloudfoam_Lifestyle_Running_Ayakkabi_Gri_IG9797_41_standard.jpg", genderId = 1, markaId = 2 },
                new Product() { Name = "Adidas Ultraboost 1.0", Subtitle = "Woman shoes", Description = "Adidas Ultraboost Running", Price = 160, Stock = 100, IsApproved = true, CategoryId = 2, IsHome = false, Image = "Ultraboost_1.0_ATR_Ayakkabi_Bej_IF9072_06_standard.jpg", Image2 = "Ultraboost_1.0_ATR_Ayakkabi_Bej_IF9072_06_standard.jpg", Image3 = "Ultraboost_1.0_ATR_Ayakkabi_Bej_IF9072_06_standard.jpg", genderId = 1, markaId = 2 },
                new Product() { Name = "Adidas Ultraboost 20", Subtitle = "Woman shoes", Description = "Adidas Ultraboost 20 Black Running", Price = 160, Stock = 100, IsApproved = true, CategoryId = 2, IsHome = false, Image = "Ultraboost_20_Ayakkabi_Siyah_FV8349_06_standard.jpg", Image2 = "Ultraboost_20_Ayakkabi_Siyah_FV8349_06_standard.jpg", Image3 = "Ultraboost_20_Ayakkabi_Siyah_FV8349_06_standard.jpg", genderId = 1, markaId = 2 },

                //woman original adidas
                new Product() { Name = "Adidas Stella Mccartney", Subtitle = "Woman shoes", Description = "Adidas Stella Mccartney", Price = 160, Stock = 100, IsApproved = true, CategoryId = 2, IsHome = false, Image = "adidas_by_Stella_McCartney_Sportswear_2000_Ayakkabi_Beyaz_IG0013_06_standard.jpg", Image2 = "adidas_by_Stella_McCartney_Sportswear_2000_Ayakkabi_Beyaz_IG0013_02_standard.jpg", Image3 = "adidas_by_Stella_McCartney_Sportswear_2000_Ayakkabi_Beyaz_IG0013_42_standard.jpg", genderId = 1, markaId = 2 },
                new Product() { Name = "Adidas Dropset 2", Subtitle = "Woman shoes", Description = "Adidas Dropset 2", Price = 160, Stock = 100, IsApproved = true, CategoryId = 2, IsHome = false, Image = "Dropset_2_Antrenman_Ayakkabisi_Mor_IF9909_06_standard.jpg", Image2 = "Dropset_2_Antrenman_Ayakkabisi_Mor_IF9909_02_standard.jpg", Image3 = "Dropset_2_Antrenman_Ayakkabisi_Mor_IF9909_42_standard.jpg", genderId = 1, markaId = 2 },
                new Product() { Name = "Adidas Y-3 RIVALRY STANDARD", Subtitle = "Woman shoes", Description = "Adidas Y-3 RIVALRY STANDARD PURPLE", Price = 160, Stock = 100, IsApproved = true, CategoryId = 2, IsHome = false, Image = "Y-3_RIVALRY_Mor_ID5499_06_standard.jpg", Image2 = "Y-3_RIVALRY_Mor_ID5499_02_standard.jpg", Image3 = "Y-3_RIVALRY_Mor_ID5499_43_standard.jpg", genderId = 1, markaId = 2 },

                 //woman training adidas
                new Product() { Name = "Adidas GAZELLE 85", Subtitle = "Woman shoes", Description = "Adidas GAZELLE 85 Woman Pink", Price = 160, Stock = 100, IsApproved = true, CategoryId = 2, IsHome = false, Image = "adidas_by_Stella_McCartney_Sportswear_2000_Ayakkabi_Beyaz_IG0013_06_standard.jpg", Image2 = "adidas_by_Stella_McCartney_Sportswear_2000_Ayakkabi_Beyaz_IG0013_02_standard.jpg", Image3 = "adidas_by_Stella_McCartney_Sportswear_2000_Ayakkabi_Beyaz_IG0013_42_standard.jpg", genderId = 1, markaId = 2 },
                new Product() { Name = "Adidas Samba", Subtitle = "Woman shoes", Description = "Adidas Samba Originals Woman Pink", Price = 160, Stock = 100, IsApproved = true, CategoryId = 2, IsHome = false, Image = "Dropset_2_Antrenman_Ayakkabisi_Mor_IF9909_06_standard.jpg", Image2 = "Dropset_2_Antrenman_Ayakkabisi_Mor_IF9909_02_standard.jpg", Image3 = "Dropset_2_Antrenman_Ayakkabisi_Mor_IF9909_42_standard.jpg", genderId = 1, markaId = 2 },
                new Product() { Name = "Adidas Y-3 RIVALRY STANDARD", Subtitle = "Woman shoes", Description = "Adidas Y-3 RIVALRY STANDARD PURPLE", Price = 160, Stock = 100, IsApproved = true, CategoryId = 2, IsHome = false, Image = "Y-3_RIVALRY_Mor_ID5499_06_standard.jpg", Image2 = "Y-3_RIVALRY_Mor_ID5499_02_standard.jpg", Image3 = "Y-3_RIVALRY_Mor_ID5499_43_standard.jpg", genderId = 1, markaId = 2 },

                //erkek original casual nike
                new Product() { Name = "Nike Dunk Low", Subtitle = "Men's Shoes", Description = "Throwback hoops flair shines bright with this Dunk Low. Created for the hardwood but taken to the streets, this sneaker icon returns with a durable leather upper and starry accents for cosmic style with every step. Its padded, low-cut collar lets you take your game anywhere—in comfort.", Price = 160, Stock = 100, IsApproved = true, CategoryId = 1, IsHome = false, Image = "Nike Dunk Low.jpg", Image2 = "Nike Dunk Low 2.jpg", Image3 = "Nike Dunk Low3.jpg", genderId = 2, markaId = 1 },
                new Product() { Name = "Nike Air Force 1 '07 LV8", Subtitle = "Men's Shoes", Description = "Comfortable, durable and timeless—it’s number 1 for a reason. The AF1's classic ‘80s construction pairs with neutral colors and layered textures for a utilitarian look.", Price = 160, Stock = 100, IsApproved = true, CategoryId = 1, IsHome = false, Image = "Nike Air Force 1 07 LV8.jpg", Image2 = "Nike Air Force 1 07 LV8 2.jpg", Image3 = "Nike Air Force 1 07 LV8.jpeg", genderId = 2, markaId = 1 },
                new Product() { Name = "Forum Low The Grinch", Subtitle = "Man Shoes", Description = "Lace up and feel the legacy. These AM90s will keep up with you on all your adventures thanks to a mix of GORE-TEX and mesh materials. Worn by presidents, revolutionized through collabs and celebrated through rare colorways, the Waffle sole, striking visuals and Nike Air cushioning keep it alive and well.", Price = 160, Stock = 100, IsApproved = true, CategoryId = 1, IsHome = false, Image = "Nike Air Max 90 GORE-TEX.jpg", Image2 = "Nike Air Max 90 GORE-TEX 2.jpeg", Image3 = "Nike Air Max 90 GORE-TEX 3.jpg", genderId = 2, markaId = 1 },
                
                //erkek running nike
                new Product() { Name = "Nike Alphafly 3 Proto", Subtitle = "Men's Shoes", Description = "Fine-tuned for marathon speed, the Alphafly 3 helps push you beyond what you thought possible. Three innovative technologies power your run: A double dose of Air Zoom units helps launch you into your next step; a full-length carbon fiber plate helps propel you forward with ease; and a heel-to-toe ZoomX foam midsole helps keep you fresh from start to 26.2. Time to leave your old personal records in the dust..", Price = 160, Stock = 100, IsApproved = true, CategoryId = 2, IsHome = false, Image = "Nike Alphafly 3 Proto.jpg", Image2 = "Nike Alphafly 3 Proto 2.jpg", Image3 = "Nike Alphafly 3 Proto 3.jpg", genderId = 2, markaId = 1 },
                new Product() { Name = "Nike InfinityRN 4 GORE-TEX", Subtitle = "Men's Shoes", Description = "With supportive cushioning built for a smooth run, the Nike InfinityRN 4 is a brand-new take on a familiar favorite. It's made from our all-new Nike ReactX foam, which gives you 13% more energy return compared with Nike React foam, to help you stay fresh and bouncy. (What's more? Nike ReactX reduces its carbon footprint in a pair of midsoles by at least 43% compared to Nike React foam.*) This version has GORE-TEX fabric to help you stay dry for your miles. It’s the kind of shoe that supports every step in style. *The carbon footprint of ReactX is based on cradle-to-gate assessment reviewed by PRé Sustainability B.V and Intertek China. Other midsole components such as airbags, plates or other foam formulations were not considered.", Price = 160, Stock = 100, IsApproved = true, CategoryId = 2, IsHome = false, Image = "Nike InfinityRN 4 GORE-TEX 1.jpg", Image2 = "Nike InfinityRN 4 GORE-TEX 2.jpg", Image3 = "Nike InfinityRN 4 GORE-TEX 3.jpg", genderId = 2, markaId = 1 },
                new Product() { Name = "Nike Vaporfly 3", Subtitle = "Man Shoes", Description = "Catch ‘em if you can. Giving you race-day speed to conquer any distance, the Nike Vaporfly 3 is made for the chasers, the racers, the elevated pacers who can’t turn down the thrill of the pursuit. We reworked the leader of the super shoe pack and tuned the engine underneath to help you chase personal bests from a 10K to marathon. From elite runners to those new to racing, this versatile road-racing workhorse is for those who see speed as a gateway to more miles and more seemingly uncatchable highs.", Price = 160, Stock = 100, IsApproved = true, CategoryId = 2, IsHome = false, Image = "Nike Vaporfly.jpg", Image2 = "Nike Vaporfly 2.jpg", Image3 = "Nike Vaporfly 3.jpg", genderId = 2, markaId = 1 },
               
                //erkek training nike
                new Product() { Name = "Nike Air Max Alpha Trainer 5", Subtitle = "Men's Shoes", Description = "Finish your last rep with power and rack it with a roar that stuns the gym floor in the Nike Air Max Alpha Trainer 5. Max Air cushioning offers comfortable stability for lifting whether it’s a light or heavy day. A wide, flat base gives you enhanced stability and grip for all kinds of tough workouts without sacrificing style, as you roam from station to station and set to set.", Price = 160, Stock = 100, IsApproved = true, CategoryId = 3, IsHome = false, Image = "Nike Air Max Alpha Trainer 5.jpg", Image2 = "Nike Air Max Alpha Trainer 5 2.jpg", Image3 = "Nike Air Max Alpha Trainer 5 3.jpg", genderId = 2, markaId = 1 },
                new Product() { Name = "Nike InfinityRN 4 GORE-TEX", Subtitle = "Men's Shoes", Description = "Whatever your  is for working out, the Metcon 9 makes it all worth it. We improved on the 8 with a larger Hyperlift plate and added rubber rope wrap. Sworn by some of the greatest athletes in the world, intended for lifters, trainers, go-getters, it’s still the gold standard that delivers day after day.", Price = 160, Stock = 100, IsApproved = true, CategoryId = 3, IsHome = false, Image = "Nike Metcon 9 AMP.jpg", Image2 = "Nike Metcon 9 AMP 2.jpg", Image3 = "Nike Metcon 9 AMP 3.jpg", genderId = 2, markaId = 1 },
                new Product() { Name = "Nike Motiva", Subtitle = "Man Shoes", Description = "The Nike Motiva helps you step through whatever the day brings, at your pace. Its uniquely patterned outsole and exaggerated rocker combine to give you a super-smooth, cushioned and comfortable ride. This means you can walk, jog or run comfortably and come back for your next leisurely stroll confidently. It gives you optimal support for your every move, every day.", Price = 160, Stock = 100, IsApproved = true, CategoryId = 3, IsHome = false, Image = "Nike Motiva.jpg", Image2 = "Nike Motiva 2.jpg", Image3 = "Nike Motiva 3.jpeg", genderId = 2, markaId = 1 },

                //kids original casual nike
                new Product() { Name = "Jordan 3 Retro", Subtitle = "Kids Shoes", Description = "Fresh like a scoop of Neapolitan ice cream on a hot day, these mini J's are more than just the flavor of the summer. Sturdy leather and premium textiles up top and supportive foam underfoot make this a solid choice for learning feet. Casual and classic, we predict these kicks will be the coolest pair on the playground.", Price = 160, Stock = 100, IsApproved = true, CategoryId = 1, IsHome = false, Image = "Jordan 3 Retro.jpg", Image2 = "Jordan 3 Retro 2.jpg", Image3 = "Jordan 3 Retro 3.jpg", genderId = 3, markaId = 1 },
                new Product() { Name = "Nike Air Max 1 EasyOn", Subtitle = "Men's Shoes", Description = "Made for kids (and their squirmy feet), these Air Max Shoes have a Nike EasyOn system that makes putting them on a breeze. The laces are just for show—the top loop combines with a hook-and-loop strap to create a wide opening while still looking like traditional laces.", Price = 160, Stock = 100, IsApproved = true, CategoryId = 1, IsHome = false, Image = "Nike Air Max 1 EasyOn.jpg", Image2 = "Nike Air Max 1 EasyOn 2.jpg", Image3 = "Nike Air Max 1 EasyOn 3.jpg", genderId = 3, markaId = 1 },
                new Product() { Name = "Nike Dunk Low", Subtitle = "Man Shoes", Description = "The Nike Dunk Low is an easy score for your kiddo’s closet. This mid-‘80s hoops icon returns with super durable construction and original colors. Ankle padding and easy elastic laces make it a slam dunk for young sneakerheads.", Price = 160, Stock = 100, IsApproved = true, CategoryId = 1, IsHome = false, Image = "Nike Dunk Low.jpg", Image2 = "Nike Dunk Low 2.jpg", Image3 = "Nike Dunk Low 3.jpg", genderId = 3, markaId = 1 },

                //nike kids running
                new Product() { Name = "Nike Air Zoom Pegasus 40", Subtitle = "Kids Shoes", Description = "40 years. Generations of running. The Pegasus 40 reps the past and future of Nike running. Whether you're gearing up for a school track meet, track practice or fun runs (like your gym class mile), this shoe is for runners of all levels. They're breathable so your feet stay cool with every lap. Zoom Air and responsive foam team up for the cushioning you need to feel comfortable with every stride. It's time to fly!", Price = 160, Stock = 100, IsApproved = true, CategoryId = 2, IsHome = false, Image = "Nike Air Zoom Pegasus 40.jpg", Image2 = "Nike Air Zoom Pegasus 40 2.jpg", Image3 = "Nike Air Zoom Pegasus 40 3.jpg", genderId = 3, markaId = 1 },
                new Product() { Name = "Nike Star Runner", Subtitle = "Men's Shoes", Description = "Get out the door in a flash with the Star Runner. Loops on the tongue and heel make it easy to open the shoe up wide so little star runners can step in and get going. Soft cushioning in the midsole provides a comfortable, springy return so 1 more round, lap and turn is always an option. The tread grabs at pavement, grass and gravel to give them extra grip while a rubber-wrapped toe toughens up the construction so they can go further in the same pair of Star Runners.", Price = 160, Stock = 100, IsApproved = true, CategoryId = 2, IsHome = false, Image = "Nike Star Runner 1.jpg", Image2 = "Nike Star Runner 2.jpg", Image3 = "Nike Star Runner 3.jpg", genderId = 3, markaId = 1 },
        
               //nike kids training
                new Product() { Name = "Ja 1 Backyard BBQ", Subtitle = "Men's Shoes", Description = "Ja Morant became the superstar he is today by practicing his game wherever and whenever he could. For him that meant sinking jumpers and dribbling through traffic cones on a concrete court his dad built. The Ja 1 Backyard BBQ honors the backyard where Ja honed his skills and hosted weekly barbecues for family and friends. Lightweight, breathable and supportive, they're ready for you to lace up and chase your own dreams from the jump.", Price = 160, Stock = 100, IsApproved = true, CategoryId = 3, IsHome = false, Image = "Ja 1 Backyard BBQ.jpg", Image2 = "Ja 1 Backyard BBQ 2.jpg", Image3 = "Ja 1 Backyard BBQ 3.jpeg", genderId = 3, markaId = 1 },
                new Product() { Name = "LeBron XXI Conchiolin", Subtitle = "Men's Shoes", Description = "Last time around, LeBron flipped the script on his shoe game as only the King can. The encore is even better. With an Air Zoom unit and soft cushioning, the LeBron XXI (also known as the LeBron 21) gives you flexibility and power without a lot of excess weight to slow you down. Ideal for rim runs, fast breaks and racing up and down the court, they help you keep playing at the top of your game until the final buzzer sounds. Are you ready to play?", Price = 160, Stock = 100, IsApproved = true, CategoryId = 3, IsHome = false, Image = "LeBron XXI Conchiolin.jpg", Image2 = "LeBron XXI Conchiolin 2.jpg", Image3 = "LeBron XXI Conchiolin 3.jpg", genderId = 3, markaId = 1 },
        


 

 
 
                //erkek original adidas
                new Product() { Name = "Adidas Campus 00s", Subtitle = "Man Shoes", Description = "Adidas Original Campus00s Gray", Price = 160, Stock = 100, IsApproved = true, CategoryId = 2, IsHome = false, Image = "Campus_00s_Ayakkabi_Gri_IE2217_06_standard.jpg", Image2 = "Campus_00s_Ayakkabi_Gri_IE2217_02_standard.jpg", Image3 = "Campus_00s_Ayakkabi_Gri_IE2217_41_detail.jpg", genderId = 2, markaId = 2 },
                new Product() { Name = "Adidas Forum Low", Subtitle = "Man Shoes", Description = "Adidas Originals", Price = 160, Stock = 100, IsApproved = true, CategoryId = 2, IsHome = false, Image = "Forum_Low_Ayakkabi_Beyaz_FY7757_06_standard.jpg", Image2 = "Forum_Low_Ayakkabi_Beyaz_FY7757_02_standard.jpg", Image3 = "Forum_Low_Ayakkabi_Beyaz_FY7757_41_standard.jpg", genderId = 2, markaId = 2 },
                new Product() { Name = "Forum Low The Grinch", Subtitle = "Man Shoes", Description = "Adidas Originals", Price = 160, Stock = 100, IsApproved = true, CategoryId = 2, IsHome = false, Image = "FORUM_LOW_THE_GRINCH_Beyaz_ID3512_06_standard.jpg", Image2 = "FORUM_LOW_THE_GRINCH_Beyaz_ID3512_02_standard.jpg", Image3 = "FORUM_LOW_THE_GRINCH_Beyaz_ID3512_41_standard.jpg", genderId = 2, markaId = 2 },
                new Product() { Name = "Adidas Ozmorph", Subtitle = "Man Shoes", Description = "Adidas Originals", Price = 160, Stock = 100, IsApproved = true, CategoryId = 2, IsHome = false, Image = "OZMORPH_Ayakkabi_Yesil_IE2025_06_standard.jpg", Image2 = "OZMORPH_Ayakkabi_Yesil_IE2025_02_standard.jpg", Image3 = "OZMORPH_Ayakkabi_Yesil_IE2025_41_standard.jpg", genderId = 2, markaId = 2 },
                new Product() { Name = "Adidas The Simpsons X Rivalry", Subtitle = "Man Shoes", Description = "Adidas Originals", Price = 160, Stock = 100, IsApproved = true, CategoryId = 2, IsHome = false, Image = "THE_SIMPSONS_(ITCHY)_x_RIVALRY_Multi_IE7566_06_standard.jpg", Image2 = "THE_SIMPSONS_(ITCHY)_x_RIVALRY_Multi_IE7566_02_standard.jpg", Image3 = "THE_SIMPSONS_(ITCHY)_x_RIVALRY_Multi_IE7566_41_standard.jpg", genderId = 2, markaId = 2 },

                //erkek running adidas
                new Product() { Name = "Adidas Galaxy 6 Running", Subtitle = "Man Shoes", Description = "Adidas Galaxy 6 Running", Price = 160, Stock = 100, IsApproved = true, CategoryId = 2, IsHome = false, Image = "Galaxy_6_Ayakkabi_Beyaz_IE1975_06_standard.jpg", Image2 = "Galaxy_6_Ayakkabi_Beyaz_IE1975_02_standard.jpg", Image3 = "Galaxy_6_Ayakkabi_Beyaz_IE1975_42_standard.jpg", genderId = 2, markaId = 2 },
                new Product() { Name = "Adidas OZWEEGO", Subtitle = "Man Shoes", Description = "Adidas Running White Shoe", Price = 160, Stock = 100, IsApproved = true, CategoryId = 2, IsHome = false, Image = "OZWEEGO_Ayakkabi_Beyaz_EE6464_06_standard.jpg", Image2 = "OZWEEGO_Ayakkabi_Beyaz_EE6464_02_standard.jpg", Image3 = "OZWEEGO_Ayakkabi_Beyaz_EE6464_41_standard.jpg", genderId = 2, markaId = 2 },
                new Product() { Name = "Adidas Ultra 4D", Subtitle = "Man Shoes", Description = "Adidas Running", Price = 160, Stock = 100, IsApproved = true, CategoryId = 2, IsHome = false, Image = "Ultra_4D_Ayakkabi_Gri_IG2260_06_standard.jpg", Image2 = "Ultra_4D_Ayakkabi_Gri_IG2260_02_standard.jpg", Image3 = "Ultra_4D_Ayakkabi_Gri_IG2260_42_standard.jpg", genderId = 2, markaId = 2 },
                new Product() { Name = "Adidas UltraBoost ", Subtitle = "Man Shoes", Description = "Adidas UltraBoost Light", Price = 160, Stock = 100, IsApproved = true, CategoryId = 2, IsHome = false, Image = "ULTRABOOST_LIGHT_Siyah_IE8155_06_standard.jpg", Image2 = "ULTRABOOST_LIGHT_Siyah_IE8155_02_standard.jpg", Image3 = "ULTRABOOST_LIGHT_Siyah_IE8155_42_standard.jpg", genderId = 2, markaId = 2 },
                new Product() { Name = "Adidas X PLR BOOST", Subtitle = "Man Shoes", Description = "Adidas X PLR BOOST BLACK", Price = 160, Stock = 100, IsApproved = true, CategoryId = 2, IsHome = false, Image = "X_PLR_Boost_Ayakkabi_Siyah_IG8506_06_standard.jpg", Image2 = "X_PLR_Boost_Ayakkabi_Siyah_IG8506_02_standard.jpg", Image3 = "X_PLR_Boost_Ayakkabi_Siyah_IG8506_43_standard.jpg", genderId = 2, markaId = 2 },    
                 
                //erkek training adidas
                new Product() { Name = "Adidas by Stella McCartney", Subtitle = "Man Shoes", Description = "Adidas SportsWear White", Price = 160, Stock = 100, IsApproved = true, CategoryId = 2, IsHome = false, Image = "adidas_by_Stella_McCartney_Sportswear_Ayakkabi_Beyaz_IG2441_06_standard_2_11zon.jpg", Image2 = "adidas_by_Stella_McCartney_Sportswear_Ayakkabi_Beyaz_IG2441_02_standard_2_11zon.jpg", Image3 = "adidas_by_Stella_McCartney_Sportswear_Ayakkabi_Beyaz_IG2441_41_standard_2_11zon.jpg", genderId = 2, markaId = 2 },
                new Product() { Name = "Adidas Everyset", Subtitle = "Man Shoes", Description = "Adidas Everyset Green Standard", Price = 160, Stock = 100, IsApproved = true, CategoryId = 2, IsHome = false, Image = "Everyset_Ayakkabi_Yesil_IF9910_06_standard_5_11zon.jpg", Image2 = "Everyset_Ayakkabi_Yesil_IF9910_02_standard_5_11zon.jpg", Image3 = "Everyset_Ayakkabi_Yesil_IF9910_42_standard_5_11zon.jpg", genderId = 2, markaId = 2 },
                new Product() { Name = "Adidas Y-3 GAZELLE", Subtitle = "Man Shoes", Description = "Adidas Training", Price = 160, Stock = 100, IsApproved = true, CategoryId = 2, IsHome = false, Image = "Y-3_GAZELLE_Yesil_IG5309_06_standard_8_11zon.jpg", Image2 = "Y-3_GAZELLE_Yesil_IG5309_02_standard_8_11zon.jpg", Image3 = "Y-3_GAZELLE_Yesil_IG5309_41_standard_8_11zon.jpg", genderId = 2, markaId = 2 },
                new Product() { Name = "Adidas Y-3 KAIWA ", Subtitle = "Man Shoes", Description = "Adidas UltraBoost Light", Price = 160, Stock = 100, IsApproved = true, CategoryId = 2, IsHome = false, Image = "Y-3_KAIWA_Siyah_IG4055_06_standard_11_11zon.jpg", Image2 = "Y-3_KAIWA_Siyah_IG4055_09_standard_11_11zon.jpg", Image3 = "Y-3_KAIWA_Siyah_IG4055_02_standard_11_11zon.jpg", genderId = 2, markaId = 2 },
                new Product() { Name = "Adidas Y-3 RIVALRY", Subtitle = "Man Shoes", Description = "Adidas Y3 RIVALRY BLACK", Price = 160, Stock = 100, IsApproved = true, CategoryId = 2, IsHome = false, Image = "Y-3_RIVALRY_Siyah_ID5431_06_standard_14_11zon.jpg", Image2 = "Y-3_RIVALRY_Siyah_ID5431_09_standard_14_11zon.jpg", Image3 = "Y-3_RIVALRY_Siyah_ID5431_02_standard_14_11zon.jpg", genderId = 2, markaId = 2 },
              

              







        };
       





            foreach (var urun in urunler)
            {
                context.Products.Add(urun);
            }

            context.SaveChanges();

            base.Seed(context);
        }
        }
}